// <auto-generated />
namespace EFcode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201604200952 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201604200952));
        
        string IMigrationMetadata.Id
        {
            get { return "201604200152273_201604200952"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
