//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myentity : DbContext
    {
        public myentity()
            : base("name=myentity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<SMS_History> SMS_History { get; set; }
        public virtual DbSet<SMS_Model> SMS_Model { get; set; }
        public virtual DbSet<Work_Invited> Work_Invited { get; set; }
        public virtual DbSet<Work_Master> Work_Master { get; set; }
    }
}
