//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_History
    {
        public int SysNo { get; set; }
        public Nullable<int> CustomerSysNo { get; set; }
        public string Mobile { get; set; }
        public string SMSContent { get; set; }
        public string SMSKey { get; set; }
        public System.DateTime SendTime { get; set; }
        public int SMSTypeSysNo { get; set; }
    }
}
