//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Master
    {
        public int SysNo { get; set; }
        public string WorkID { get; set; }
        public int CategorySysNo { get; set; }
        public bool IsStandard { get; set; }
        public string WorkName { get; set; }
        public string Introduction { get; set; }
        public string SkillSysNos { get; set; }
        public string RequestSysNos { get; set; }
        public decimal BudgetAmt { get; set; }
        public decimal FeeAmt { get; set; }
        public int GradeSysNo { get; set; }
        public int TimeSpanSysNo { get; set; }
        public int WorkVisibleSysNo { get; set; }
        public int AimCustomerTypeSysNo { get; set; }
        public string WorkFileSysNos { get; set; }
        public Nullable<int> ScoreLevelSysNo { get; set; }
        public Nullable<int> AimLocationSysNo { get; set; }
        public string OtherRequests { get; set; }
        public string DevelopPlatformSysNos { get; set; }
        public Nullable<int> ProjectStatusSysNo { get; set; }
        public Nullable<int> ProjectKindSysNo { get; set; }
        public string ProjectTypeSysNos { get; set; }
        public Nullable<int> DevelopRoleSysNos { get; set; }
        public Nullable<bool> IsOnlineDevelopment { get; set; }
        public string SocialAPISysNos { get; set; }
        public int CreateCustomerSysNo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Note { get; set; }
        public int Status { get; set; }
        public Nullable<int> Schedule { get; set; }
        public Nullable<int> WorkUserSysNo { get; set; }
        public Nullable<System.DateTime> ProjectTime { get; set; }
        public int PayStatus { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int WorkStep { get; set; }
        public Nullable<int> FlowSysNo { get; set; }
    }
}
