//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Invited
    {
        public int SysNo { get; set; }
        public int WorkMasterSysNo { get; set; }
        public int InviteCustomerSysNo { get; set; }
        public int InvitedCustomerSysNo { get; set; }
        public System.DateTime InviteTime { get; set; }
        public int InviteResult { get; set; }
        public Nullable<int> InvitedUserType { get; set; }
        public int InviteType { get; set; }
    }
}
